config/routes.rb
Rails.application.routes.draw do
  #main
  root 'posts#index', as: 'home'
  #url's
  get 'about' => 'pages#about', as: 'about'
  #отслеживание ссылок внутри url-адресов;
  resources :posts do resources :comments end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum: 1}
  #Привязка к комментариям;
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    #Поиск конкретного поста
    @post = Post.find(params[:post_id])
    #Создание комментария
    @comment = @post.comments.create(comments_params)
    #перенаправить к посту
    redirect_to post_path(@post)
  end
  #приватный метод для коммента
  private def comments_params
    #данные коммента
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    #Функционал;
    @header = 'Страница обо мне.'
    @heading = 'Пара lorem ipsum.'
    @text = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'qwerty', except:[:index, :show]

  def index
    #Функционал;
    #Показываем все статьи из DB
    @post = Post.all
  end

  def new
    #Новые посты;
    @post = Post.new
  end
  #показать посты
  def show
    @post = Post.find(params[:id])
  end
  #изменение
  def edit
    @post = Post.find(params[:id])
  end
  #обновить после правок
  def update
    @post = Post.find(params[:id])
    if(@post.update(post_params))
    #Перенаправление
    redirect_to @post
    #Но если ошибка - вернуть к редактированию
    else
      render 'edit'
    end
  end

  def create
    # render plain: params[:post].inspect
    #Получаем параметры от формы с указанием типа;
    @post = Post.new(post_params)
    #сохраняем
    if(@post.save)
    #Перенаправление
    redirect_to @post
    #Если не прошла проверка
    else
      render 'new'
    end
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end

  #Удаление статьи;
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to home_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogWithBootstrap4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-danger text-white border-bottom shadow p-3 mb-5">
          <h5 class="my-0 mr-md-auto font-weight-bold">Блог на Ruby on Rails + Bootstrap 4</h5>
          <nav class="my-2 my-md-2 mr-md-2">

            <span class="btn btn-light p-7">
              <%= link_to "На главную", home_path %>
            </span>

            <span class="btn btn-light p-7">
              <%= link_to "Обо мне", about_path %>
            </span>

            <span class="btn btn-light p-7">
              <%= link_to "Добавить статью", new_post_path %>
            </span>

          </nav>

        </div>

    <div class="container">
      <%= yield %>
      <hr>
      <footer class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-danger text-white border-bottom shadow p-3 mb-5">Rails Blog, est.2018</footer>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<section class="section_main">
  <h2 class="card-title"> <%= @header %> </h2>
  <div class="card-body shadow p-3 mb-5">
    <p class="card-text"> <%= @heading %> </p>
    <p> <%= @text %> </p>
    <p> <%= @text %> </p>
  </div>
</section>

app/views/posts/edit.html.erb
<section class="section">
  <div class="post">
    <h3 class="post_header">Редактирование статьи</h3>
    <div class="shadow p-3 mb-5"">
    <%= form_for :post, url: post_path(@post), method: :patch do |f| %>
      <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
    <p class="post_name">Название поста: <br>
      <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p class="post_body">Содержание поста: <br>
      <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p class="post_create">
      <%= f.submit('Сохранить изменения', {:class => 'btn btn-warning text-white'})%>
    </p>
    <% end %>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<section class="section_main">
  <h2 class="header">Главная страница блога</h2>
  <div class="card-body shadow p-3 mb-5">
    <p class="card-text">Пара lorem об этом блоге</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat.</p>
  </div>
  <div class="card-body shadow p-3 mb-5">
    <p class="card-text">Здесь вы можете посмотреть историю изменений по веткам:</p>
    <a href="https://github.com/Ketzenkrad/RailsBlog" class="text-info">Ссылка на Github.</a>
  </div>
  <div class="card-body">
    <h2 class="card-title">Все статьи этого блога:</h2>
    <% @post.each do |post| %>
    <div class="card-body shadow p-3 mb-5">
      <h3 class="card-title"> <%= post.title %> </h3>
      <p class="card-text"> <%= post.body %> </p>
      <%= link_to "Читать далее.. ►", post_path(post), class: "btn btn-danger" %>
    </div>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<section class="section">
  <div class="post">
    <h3 class="post_header">Добавление поста</h3>
    <div class="shadow p-3 mb-5"">
    <%= form_for :post, url: posts_path do |f| %>
      <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
    <p class="post_name">Название поста: <br>
      <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p class="post_body">Содержание поста: <br>
      <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p class="post_create">
      <%= f.submit('Создать пост ✎', {:class => 'btn btn-danger text-white'})%>
    </p>
    <% end %>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="current_posts">

<div class="card-body shadow p-3 mb-5">
<div class="card-body">
    <h2 class="card-title"> <%= @post.title %> ✒</h2>
    <p class="card-text"> <%= @post.body %> </p>
    <%= link_to "Редактировать статью ✑", edit_post_path(@post), :class => 'btn btn-success'%>
    <%= link_to "Удалить статью ⚠ ", post_path(@post), method: :delete, data: {confirm:"⚠ Вы уверены? Статья будет удалена. ⚠"}, :class => 'btn btn-warning'%>
</div>
</div>

<hr>

<div class="card-body">
  <h2 class="card-title">Комментарии к статье ☑</h2>
  <% @post.comments.each do |comment| %>
  <div class="card-body shadow p-3 mb-5">
    <p class="card-text text-secondary">Пользователь <span class="text-danger"><%= comment.username %></span> оставил комментарий:</p>
    <p class="card-text"><span class=""><%= comment.body %></span></p>
  </div>
  <% end %>
</div>

<hr>

<div class="card-body">
  <h3 class="card-title">Добавить комментарий ⌨</h3>
  <div class="shadow p-3 mb-5"">
  <%= form_for([@post, @post.comments.build]) do |f| %>
  <p class="card-text">Пользователь (ник, имя) <br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>
  <p class="card-text">Содержание комментария <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p class="card-text">
    <%= f.submit('Добавить комментарий ✉', {:class => 'btn btn-danger text-white'})%>
  </p>
  <% end %>
  </div>
</div>

</section>